# Generated by Django 4.2.7 on 2026-04-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by_user_id', models.CharField(db_index=True, max_length=64)),
                ('submitted_by_name', models.CharField(max_length=255)),
                ('hazard_types', models.JSONField(default=list)),
                ('other_hazard', models.CharField(blank=True, max_length=500)),
                ('building', models.CharField(max_length=255)),
                ('floor', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('specific_location', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='report_photos/%Y/%m/')),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assessed', 'Assessed'), ('in_progress', 'In Progress'), ('closed', 'Closed')], db_index=True, default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
